language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules

before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

script:
  - docker build -t marcelomaia/portal_uniforme_frontend .
  - docker run -d -p 8080:80 marcelomaia/portal_uniforme_frontend
  - docker ps -a

deploy:
  provider: script
  script: bash utility/deploy_dockerhub.sh
  on:
    all_branches: true